### ISSUE TITLE
Issue 1 - User can create a trip

### ISSUE THREAD

**Issue by wang-lawrence** [wang-lawrence/Trippie#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a trip

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to name their trip and select the start and end date for their trip

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="291" alt="image" src="https://github.com/wang-lawrence/Trippie/assets/130196412/e0d72f9b-001f-46c5-9c7d-dcee86128db6">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
- [ ] Create route methods the event endpoint at `api/event`
- [ ] Create the static React components 
  - [ ] Navbar
  - [ ] FormComponent
  - [ ] Add background image
- [ ] Add onSubmit event listener to the `Start New Trip` button to handle form submission

### 🐘 Database Tasks

- [ ] None

### ☁️ Server Tasks

- [ ] Create route methods the event endpoint at `api/event`
    - [ ] `get`  - get all events
    - [ ] `post`  - inset a new event
    - [ ] `put` - edit an event
    - [ ] `delete` - delete an event
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create the static React components 
  - [ ] Navbar
  - [ ] FormComponent
    - [ ] Trip Name input
    - [ ] Start Date select box
    - [ ] End Date select box
    - [ ] Start New Trip button
  - [ ] Add background image
- [ ] Add onSubmit event listener to the `Start New Trip` button, event handler should be async and have
  - [ ] e.preventDefault()
  - [ ] fetch post FormData to the `api/event ` endpoint
  - [ ] switch view to Saved Trips Component (issue 2) with React Router link

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
